### PR TITLE
Reregister if we get only readable or writable

### LINKED ISSUE #161: [epoll] Reactor does not register interest in some cases. Issue introduced after read_with/write_with commit.
I updated to the latest smol on a pet project that uses UnixStream for communication and I notice that in some cases communication was getting stuck on `epoll_wait`.

I did bisect on smol and the first bad commit is 76aa1ea654a322d0abaf4291dde2eb5d89c50205.

I also created a minimal reproducible example: https://github.com/oblique/smol-epoll-issue

Something that I noticed is that if I switch from UnixStream to TcpStream, the bug is not reproducible anymore.

To reproduce it do:

* Clone `smol-epoll-issue`
* Run: `cargo run --bin server`
* Run: `cargo run --bin client`
* Client will start printing some text
* After some seconds text printing will get stuck

### PR DESCRIPTION
**Pull request by sopium**
but we are interested in both. Fix #161.

### CODE REVIEW

File: src/reactor.rs [hunk 1]
```diff
@@ -293,6 +293,19 @@ impl ReactorLock<'_> {
...
+                            // previously interested in both readability and
+                            // writability, but only one of them was emitted.
+                            if !(wakers.writers.is_empty() && wakers.readers.is_empty()) {
+                                self.reactor.sys.reregister(
+                                    source.raw,
+                                    source.key,
+                                    !wakers.readers.is_empty(),
+                                    !wakers.writers.is_empty(),
+                                )?;
+                            }
```
Comment (sopium) [inline src/reactor.rs:308]: There is an issue here: if the event is neither readable or writable (e.g. merely a EPOLLHUP), we are in a busy loop.

It should be fixed by #134.
